remoteproc: qcom: q6v5: Use _clk_get_optional for aggre2_clk
Follow up commit 6d967a5a49 ("remoteproc: qcom: q6v5: Use
_clk_get_optional for aggre2_clk") to avoid below error:

error: field designator 'has_aggre2_clk' does not refer to any
       field in type 'const struct adsp_data'

Change-Id: Ie59d01c62332c5d7741950ebfdc1c590a6abba45
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>