qcom-io-pgtable-alloc: Use fixed width src vm bitmap
Align with commit 968a26a07f ("firmware: qcom_scm: Use fixed width src
vm bitmap") to avoid below error:

error: incompatible pointer types passing 'unsigned int *' to parameter
       of type 'u64 *' (aka 'unsigned long long *') [-Werror,
       -Wincompatible-pointer-types]

Change-Id: I8bd493b10762323d2d03d09ed3eabac6333c196d
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>