ANDROID: GKI: Clean up: Remove protectred lists
Follow up commit b3bbca0dc7 ("ANDROID: GKI: Clean up: Remove protectred
lists") to avoid below errors:

ERROR: kernel_platform/msm-kernel/BUILD.bazel:294:21:
       Middleman _middlemen/msm-kernel_Ssun_Uperf_Udist-runfiles
       failed: missing input file
       '//msm-kernel:android/gki_protected_modules'

Change-Id: I5a60323620321988f739a7b1198e8dea899574bb
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>