irqchip/qcom-pdc: change include path for qcom_scm.h
commit 3bf90eca76 ("firmware: qcom_scm: Move qcom_scm.h to
include/linux/firmware/qcom/") moved qcom_scm.h, align with
it to avoid below error:
fatal error: 'linux/qcom_scm.h' file not found

Change-Id: I65ddfe047814a2c73ec095e4eebd84ecc07ee1fc
Signed-off-by: Gokul krishna Krishnakumar <quic_gokukris@quicinc.com>
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>