treewide: change include path for qcom_scm.h
commit 3bf90eca76 ("firmware: qcom_scm: Move qcom_scm.h to
include/linux/firmware/qcom/") moved qcom_scm.h, align with
it to avoid below error:

fatal error: 'linux/qcom_scm.h' file not found

Change-Id: Idb0c541ad8d69037323eb725937ec2b0702104fc
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>