arm64: defconfig: Disable CONFIG_INTERCONNECT_TEST for Sun
Interface icc_get() is removed by commit 7dcdad6f32 ("interconnect: drop
unused icc_get() interface"). Replacement will be imported later.

Fixes below errors:

drivers/interconnect/debugfs-test.c:41:9: error: call to undeclared
function 'icc_get'; ISO C99 and later do not support implicit function
declarations [-Wimplicit-function-declaration]

drivers/interconnect/debugfs-test.c:41:7: error: incompatible integer to
pointer conversion assigning to 'struct icc_path *' from 'int'
[-Wint-conversion]

Change-Id: I6e9f447a6b1a3204a33c0fa93b69d1cd8ee61e98
Signed-off-by: Mike Tipton <quic_mdtipton@quicinc.com>
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>