clk: qcom: branch: Clean up branch enable registers
Follow up b96fbb03fbc ("clk: qcom: branch: Clean up branch enable
registers") to avoid below errors:

drivers/clk/qcom/clk-branch.c:63:18: error: use of undeclared identifier 'BRANCH_CLK_OFF'
drivers/clk/qcom/clk-branch.c:63:37: error: use of undeclared identifier 'BRANCH_CLK_OFF'

Change-Id: I67cc9d42b6c7ce83effafa5eb6f1e3a1c970ce03
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>