rpmsg: glink: smem: Wrap driver context
Follow up commit ab9fdd41d9 ("rpmsg: glink: smem: Wrap driver
context") to avoid below errors:

error: declaration of 'struct qcom_glink' will not be visible
       outside of this function [-Werror,-Wvisibility]

error: incompatible pointer types passing 'struct qcom_glink_smem *'
       to parameter of type 'struct qcom_glink *'
       [-Werror,-Wincompatible-pointer-types]

Change-Id: If757c69d47d868abbd65daed4615577edeeddfbe
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>