sched/walt: Fix compiler error of "do_each_thread"
Fix compiler error: implicit declaration of function
"do_each_thread". do_each_thread is deprecated.

Change-Id: I2c8fe4d815dc9dc7c8c6b37e59a532a8a1668548
Signed-off-by: jianzhou <quic_jianzhou@quicinc.com>